language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
os:
  - linux
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -r dev-requirements.txt
script:
  - pytest pyworkforce/ --verbose --color=yes --assert=plain --cov-fail-under=95 --cov-config=.coveragerc --cov=./
after_success:
  - codecov
