language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -r dev-requirements.txt
script:
  - pytest tests/ --cov-config=.coveragerc
after_success:
  - codecov
